# Generated by Django 3.1.3 on 2020-11-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.IntegerField()),
                ('second_number', models.IntegerField()),
                ('summa', models.IntegerField()),
                ('division', models.FloatField()),
                ('multiply', models.IntegerField()),
                ('minus', models.IntegerField()),
            ],
        ),
    ]
